package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_ASSIGNMENT_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tester/jenkins/workspace/zulu8-build-macos-aarch64/zulu-src/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, January 13, 2022 6:45:13 AM PST
*/

public interface ID_ASSIGNMENT_POLICY_ID
{

  /**
  	 * The value representing ID_ASSIGNMENT_POLICY_ID.
  	 */
  public static final int value = (int)(19L);
}
